### PR TITLE
LRAC-7886 Add assert site reports is AC home page upon login

### PR DESCRIPTION
**Pull request by calvinctvo**

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
hey @calvinctvo , LGTM!

**Pull request closed without merging**
